### ISSUE TITLE
Will changes in tsvcc.txt merged into tsvcc.json?

### ISSUE THREAD

**Issue by alexchanwk** [JULAC-SYS/TSVCC#1]
I can see new items being added into tsvcc.txt, but tsvcc.json is not updated yet.
Will the changes merged into the file in JSON format?

**Comment by hlhwong** [comment]
Hi, I think the tsvcc.json file has been updated accordingly. Can you check again? Thanks!

**Comment by alexchanwk** [comment]
Many thanks!
